### ISSUE TITLE
demo video

### ISSUE THREAD

**Issue by maxogden** [timkurvers/wowser#44]
hey I don't have WoW installed but i'm curious what this looks like!

**Comment by timkurvers** [comment]
Hi! At present progress is a bit split on two levels. There's `console.log` output on all authentication and game packets over WebSockets, such as when a monster moves in your vicinity.

None  of these game packets are currently processed so that any entities appear in the game world. But statically there's been some progress on rendering the game world:

![screen shot 2015-06-22 at 17 57 51](https://cloud.githubusercontent.com/assets/378235/9098169/6757e8ae-3bc8-11e5-8381-8f515be62ee1.png)
![screen shot 2015-06-22 at 17 57 19](https://cloud.githubusercontent.com/assets/378235/9098168/6756f44e-3bc8-11e5-9f4c-f2e8e686cf2c.png)

**Comment by petersandor** [comment]
I think that we should add some images to readme. +cool factor

**Comment by timkurvers** [comment]
@petersandor Agreed! Have added a preliminary screenshot :smile:

**Comment by timkurvers** [comment]
@maxogden It took a while, but there's a demo video in the README now!

**Comment by maxogden** [comment]
excellent :D
